language: c++

sudo: false

compiler:
  - g++

script: 
  - make
  - make test
  - make gcov

env:
  global:
    - CODECOV_TOKEN=d9615cc8-fdef-4123-9cf2-afb9f9f9687c

after_success:
  - bash <(curl -s https://codecov.io/bash)
